name: NuGet Gallery Push

on:
  release:
    types: [published]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: NuGet Installation
      uses: nuget/setup-nuget@v1
      with: 
        nuget-version: "latest"
    - name: MSBuild Installation
      uses: microsoft/setup-msbuild@v1.3
    - name: Dependency Restoration
      run: nuget restore "Kernel Simulator.sln"
    - name: Solution Compilation
      run: msbuild "Kernel Simulator.sln" /p:DefineConstants=NTFSCorruptionFix /p:Configuration=Release
    - name: NuGet Preparation
      run: nuget setApiKey ${{ secrets.NUGET_APIKEY }}
    - name: Package Publication
      run: |
        $path = "Kernel Simulator\KSBuild"
        $FileName = Get-ChildItem -Path $path -Recurse -Name -Filter "*symbols*"
        nuget push "$path\$FileName" -source "nuget.org"
        
